
//thunk - get from IPFS
const GET_USER_DOCUMENTS = 'GET_USER_DOCUMENTS'
const GET_USER_PRODUCTS = 'GET_USER_PRODUCTS'

//thunk - save to ipfs
const SAVE_USER_DOCUMENTS = 'SAVE_USER_DOCUMENTS'
const SAVE_USER_PRODUCTS = 'SAVE_USER_PRODUCTS'

//Put on State
const SET_USER_DOCUMENTS = 'SET_USER_DOCUMENTS'
const SET_USER_PRODUCTS = 'SET_USER_PRODUCTS'

const LOADING_USER_DOCUMENTS = 'LOADING_USER_DOCUMENTS'
const LOADING_USER_PRODUCTS = 'LOADING_USER_PRODUCTS'

const LOADED_USER_DOCUMENTS = 'LOADED_USER_DOCUMENTS'
const LOADED_USER_PRODUCTS = 'LOADED_USER_PRODUCTS'


//
const SAVED_USER_DOCUMENTS = 'SAVED_USER_DOCUMENTS'
const SAVED_USER_PRODUCTS = 'SAVED_USER_PRODUCTS'




export default {
  SET_USER_DOCUMENTS,
  SET_USER_PRODUCTS,
  GET_USER_DOCUMENTS,
  GET_USER_PRODUCTS,
  LOADING_USER_DOCUMENTS,
  LOADING_USER_PRODUCTS,
  SAVED_USER_DOCUMENTS,
  SAVED_USER_PRODUCTS,
  SAVE_USER_DOCUMENTS,
  SAVE_USER_PRODUCTS,
  LOADED_USER_DOCUMENTS,
  LOADED_USER_PRODUCTS,
};
