const IPFS_STATUS = 'IPFS_STATUS';
const IPFS_CAT = 'IPFS_CAT';
const IPFS_ADD = 'IPFS_ADD';
const IPFS_REQ_PENDING = 'IPFS_REQ_PENDING';
const IPFS_REQ_READY = 'IPFS_REQ_READY';


export default {
  IPFS_STATUS,
  IPFS_CAT,
  IPFS_ADD,
  IPFS_REQ_PENDING,
  IPFS_REQ_READY
};
