const UPDATE_WEB3_STATUS = 'web3/status/update';

const GET_USER_ACOUNTS = 'GET_USER_ACOUNTS'
const GET_BALANCE = 'GET_ACCOUNT_BALANCE'

const SET_USER_ACCOUNTS = 'SET_USER_ACCOUNTS'
const SET_USER_BALANCE = 'SET_USER_BALANCE'

const SET_WEB3_FETCH = 'SET_WEB3_FETCH'



export default {
  UPDATE_WEB3_STATUS,
  GET_USER_ACOUNTS,
  GET_BALANCE,
  SET_USER_ACCOUNTS,
  SET_USER_BALANCE,
  SET_WEB3_FETCH,
};
