const ORBIT_INSTANCE = 'ORBIT_INSTANCE';
const ORBIT_DATABASE = 'ORBIT_DATABASE';
const ORBIT_ADD = 'ORBIT_ADD';
const ORBIT_GET = 'ORBIT_GET';
const ORBIT_STATUS = 'ORBIT_STATUS';

export default {
	ORBIT_INSTANCE,
	ORBIT_DATABASE,
	ORBIT_ADD,
  ORBIT_GET,
  ORBIT_STATUS
};
