const CONTRACT_LOADING = 'CONTRACT_LOADING';
const GET_ALL_STORES = "GET_ALL_STORES";
const SET_ALL_STORES = "SET_ALL_STORES";
const GET_STORE = 'GET_STORE';
const SET_STORE = 'SET_STORE';
const USER_STORE_EXISTS = 'USER_STORE_EXISTS';



export default {
  CONTRACT_LOADING,
  GET_STORE,
  SET_STORE,
  GET_ALL_STORES,
  SET_ALL_STORES,
  USER_STORE_EXISTS
}
