const CONTRACT_LOADING = 'CONTRACT_LOADING';
const GET_TOTAL_STORES = 'GET_TOTAL_STORES';
const SET_TOTAL_STORES = 'SET_TOTAL_STORES';

export default {
  CONTRACT_LOADING,
  GET_TOTAL_STORES,
  SET_TOTAL_STORES,
}
